version: '2'
services:
  jenkins2:
    image: jenkinsci/jenkins:latest
    ports:
     - "8080:8080"
     - "50000:50000"
    volumes_from:
     - databox
    depends_on:
     - databox
  databox:
    image: busybox
    volumes:
      - ./log:/var/log/jenkins
      - ./jenkins_home:/var/jenkins_home
